### ISSUE TITLE
File uploads fail randomly

### ISSUE THREAD

**Issue by Tronic** [droppyjs/droppy#87]
Some file uploads fail silently on client side (the upload bar appears to complete, nothing on console either). The uploaded file just doesn't appear on the folder. On server side I see

```
POST /!/upload?vId=0&to=/(...)&rename=0 [200] [1ms] Upload started
POST /!/upload?vId=0&to=/(...)&rename=0 [200] [83ms] Upload cancelled
POST /!/upload?vId=0&to=/(...)&rename=0 [200] [89ms] Received 1 files
[ERROR] ENOENT: no such file or directory, rename '/(...)/.droppy/files/(name).droppy-upload' -> '/(...)/.droppy/files/(name)'
```

Where for the same file if successful the log only says

```
POST /!/upload?vId=0&to=/(...)&rename=0 [200] [0ms] Upload started
POST /!/upload?vId=0&to=/(...)&rename=0 [200] [196ms] Received 1 files
```

The Droppy is proxied through Caddy, default settings, nothing special. I recently migrated from Nginx to Caddy but I think I saw this problem before that as well.

**Comment by markhughes** [comment]
It looks like it's getting "Upload cancelled" so need to work out why that's happening. But non the less, it should at least report back with the true status

**Comment by Tronic** [comment]
The problem probably started when I replaced Nginx with Caddy. Something is different with the proxying, it would seem.

**Comment by kirillzhosul** [comment]
Actually getting that error after cancelling uploading for directory to server

**Comment by kirillzhosul** [comment]
This is one problem that stops me from using Droppy (for me seems to fail pretty fast and not so much info about)

**Comment by Tronic** [comment]
I'm not entirely sure but it seems to finish the upload and then fails silently. Mostly working with small files so it is hard to tell. Also if uploading multiple files in one operation, some might transfer and others not but transfer bars appear for all.

**Comment by LeoVasanko** [comment]
> This is one problem that stops me from using Droppy (for me seems to fail pretty fast and not so much info about)

This problem was a showstopper for us. Since it and a few other issues didn't get fixed, we set to recreate all of "Droppy" from scratch. It reads Droppy config file and can accept the existing login/password your users had, so it should be an easy replacement.

It's not quite there yet - something I expect to take a few more days as development is progressing quickly - but anyone willing to give it a try are encouraged to test it [edit: test site and Droppy links removed as no longer functional]. Also let me know if you have interest on joining the development.

Notable features include:
- Fixing all known open Droppy issues!
- WebSocket file transfers for extra speed (parallel connections to increase throughput)
- Keyboard navigation (arrow keys, shift to select, space to toggle selections, enter to view/download etc)
- Instead of copy&paste semantics for file ops, just select any items you need, navigate to target folder, and click a button to copy/move/delete/download all selected items
- Download to folder (new FileSystem API, don't need to ZIP to download directory trees)
- Like Droppy realtime directory updates by watching, full file list kept on client for quick searches and browsing without latency

**Comment by LeoVasanko** [comment]
I've now replaced our four Droppy instances in production with Cista.

Demo https://drop.zi.fi/#/
Sources https://git.zi.fi/Vasanko/cista-storage

Use `cista --import-droppy` for a quick start.

**Comment by markhughes** [comment]
> I've now replaced our four Droppy instances in production with Cista.

Hey Leo awesome work! the repo is down sadly, but as a quit note the whole point of forking this archived project into its own thing was for the community to contribute back fixing & saving Droppy (its been mostly me and a few others) but our time is very limited :) 

Please feel free to submit your fixes to https://github.com/droppyjs/droppy/pulls (unless you are just plugging a rebuild with an import command haha) notably there has been work behind the scenes to bring it up to ESM while maintaining the same database structure that you can contribute to as well if you'd like!
